#http://localhost:8080/swagger-ui.html
openapi: 3.0.1
info:
  title: API Biblioteca
  description: API REST de gerenciamento de biblioteca — autores, livros, exemplares e empréstimos.
  version: 1.0.0
  contact:
    name: Emmanoel
    email: emmanoel@biblioteca.com
servers:
  - url: http://localhost:8080
    description: Servidor local
paths: { }